import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        // Colour roles — light theme (:root)
        primary:              'var(--color-primary)',
        'on-primary':         'var(--color-on-primary)',
        'primary-container':  'var(--color-primary-container)',
        'on-primary-container': 'var(--color-on-primary-container)',
        secondary:            'var(--color-secondary)',
        'on-secondary':       'var(--color-on-secondary)',
        'secondary-container':'var(--color-secondary-container)',
        'on-secondary-container': 'var(--color-on-secondary-container)',
        tertiary:             'var(--color-tertiary)',
        'on-tertiary':        'var(--color-on-tertiary)',
        'tertiary-container': 'var(--color-tertiary-container)',
        'on-tertiary-container': 'var(--color-on-tertiary-container)',
        error:                'var(--color-error)',
        'on-error':           'var(--color-on-error)',
        'error-container':    'var(--color-error-container)',
        'on-error-container': 'var(--color-on-error-container)',
        background:           'var(--color-background)',
        'on-background':      'var(--color-on-background)',
        surface:              'var(--color-surface)',
        'on-surface':         'var(--color-on-surface)',
        'surface-variant':    'var(--color-surface-variant)',
        'on-surface-variant': 'var(--color-on-surface-variant)',
        outline:              'var(--color-outline)',
        'outline-variant':    'var(--color-outline-variant)',
        'inverse-surface':    'var(--color-inverse-surface)',
        'inverse-on-surface': 'var(--color-inverse-on-surface)',
        'inverse-primary':    'var(--color-inverse-primary)',
        'surface-dim':        'var(--color-surface-dim)',
        'surface-bright':     'var(--color-surface-bright)',
        'surface-container-lowest':  'var(--color-surface-container-lowest)',
        'surface-container-low':     'var(--color-surface-container-low)',
        'surface-container':         'var(--color-surface-container)',
        'surface-container-high':    'var(--color-surface-container-high)',
        'surface-container-highest': 'var(--color-surface-container-highest)',
      },
      fontFamily: {
        heading: 'var(--font-heading)',
        body:    'var(--font-body)',
        accent:  'var(--font-accent)',
      },
      fontSize: {
        xs:   'var(--text-xs)',
        sm:   'var(--text-sm)',
        base: 'var(--text-base)',
        lg:   'var(--text-lg)',
        xl:   'var(--text-xl)',
        '2xl': 'var(--text-2xl)',
        '3xl': 'var(--text-3xl)',
        '4xl': 'var(--text-4xl)',
        '5xl': 'var(--text-5xl)',
      },
      lineHeight: {
        none:    'var(--leading-none)',
        tight:   'var(--leading-tight)',
        snug:    'var(--leading-snug)',
        normal:  'var(--leading-normal)',
        relaxed: 'var(--leading-relaxed)',
        loose:   'var(--leading-loose)',
      },
      letterSpacing: {
        tighter:  'var(--tracking-tighter)',
        tight:    'var(--tracking-tight)',
        normal:   'var(--tracking-normal)',
        wide:     'var(--tracking-wide)',
        wider:    'var(--tracking-wider)',
        widest:   'var(--tracking-widest)',
      },
      fontWeight: {
        thin:       'var(--font-weight-thin)',
        extralight: 'var(--font-weight-extralight)',
        light:      'var(--font-weight-light)',
        normal:     'var(--font-weight-normal)',
        medium:     'var(--font-weight-medium)',
        semibold:   'var(--font-weight-semibold)',
        bold:       'var(--font-weight-bold)',
        extrabold:  'var(--font-weight-extrabold)',
        black:      'var(--font-weight-black)',
      },
      minWidth: {
        touch: '44px',
      },
      minHeight: {
        touch: '44px',
      },
    },
  },
  plugins: [],
};

export default config;
